GOOSE_MODEL: gpt-4o
GOOSE_PROVIDER: github_copilot
extensions:
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
