extensions:
  brave-search:
    args:
    - -y
    - '@modelcontextprotocol/server-brave-search'
    bundled: null
    cmd: npx
    description: null
    enabled: true
    env_keys:
    - BRAVE_API_KEY
    envs: {}
    name: brave-search
    timeout: 60
    type: stdio
  computercontroller:
    bundled: true
    display_name: Computer Controller
    enabled: true
    name: computercontroller
    timeout: 300
    type: builtin
  developer:
    bundled: true
    display_name: Developer Tools
    enabled: true
    name: developer
    timeout: 300
    type: builtin
  memory:
    bundled: true
    display_name: Memory
    enabled: true
    name: memory
    timeout: 300
    type: builtin
GOOSE_MODEL: gemini-2.0-flash
GOOSE_PROVIDER: google
